### ISSUE TITLE
不论怎么调都提示显存不足

### ISSUE THREAD

**Issue by AssedMoutain** [bilibili/ailab#38]
版本：RealCUGAN_for_win10_torch1.10.0cu111
模型：up4x-latest-conservative.pth
终端：win10,笔记本电脑 显卡 2080SUPER
CUDA版本：11.6
_CudaDeviceProperties(name='NVIDIA GeForce RTX 2080 Super', major=7, minor=5, total_memory=8191MB, multi_processor_count=48)
*********************************************************************************************************************************************
设置：tile=0
           half=False
           scale:4
提示：RuntimeError: CUDA out of memory. Tried to allocate 4.10 GiB (GPU 0; 8.00 GiB total capacity; 3.19 GiB already allocated; 2.93 GiB free; 3.21 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
*********************************************************************************************************************************************
设置：tile=4
           half=False
           scale:4
提示：RuntimeError: CUDA out of memory. Tried to allocate 280.00 MiB (GPU 0; 8.00 GiB total capacity; 6.12 GiB already allocated; 0 bytes free; 6.17 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
*********************************************************************************************************************************************
设置：tile=4
           half=True
           scale:4
提示：RuntimeError: CUDA out of memory. Tried to allocate 138.00 MiB (GPU 0; 8.00 GiB total capacity; 5.56 GiB already allocated; 0 bytes free; 6.31 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by lj1995-computer-vision** [comment]
你的分辨率图像估计很高。周末我会更新一个低显存模式，敬请期待。

**Comment by lj1995-computer-vision** [comment]
@AssedMoutain 来试试20220220版本（新增低显存模式）？
config里：
half写True
tile写5
cache_mode按顺序写0、1、2（直到显存够为止。如果2还不够，tile再往大得写）

**Comment by AssedMoutain** [comment]
@lj1995-computer-vision 
新版本完美解决了这个问题，确实是输入的图片分辨率过大导致。
